FROM python:3

WORKDIR /usr/src/app

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD rm -f djreact/settings.py && cp djreact/settings_dev.py djreact/settings.py && ./manage.py runserver 0.0.0.0:8000
